[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "G3CAYKc3b2WDshEqtGGArr8JEaL5wu3zQzWwEtyPyNUW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
